services:
  - type: web
    name: zenov-api
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn render_api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: SIGNALCARE_TO_EMAIL
        value: contact@zenov.io
      - key: SIGNALCARE_CC_EMAIL
        value: zenovou@gmail.com
      - key: SIGNALCARE_FROM_EMAIL
        value: Zenov Website <contact@zenov.io>
      - key: ZENOV_ENV
        value: PRODUCTION
